spring:
  application:
    name: ai-game
  profiles:
    active: local
    
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/ai_chatting_web?useSSL=false&serverTimezone=UTC&characterEncoding=utf8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update       # 或者 none / create / create-drop / validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      
  # JSON序列化配置
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    date-format: yyyy-MM-dd
    time-zone: Asia/Shanghai
      
  # Flyway配置
  flyway:
    enabled: true
    baseline-on-migrate: true

# 日志配置
logging:
  level:
    org:
      springframework: INFO
    com:
      ruguiima:
        AIGame: DEBUG

# DeepSeek 配置
deepseek:
  api-key: ${DEEPSEEK_API_KEY}
  base-url: https://api.deepseek.com
  model: deepseek-chat
  max-messages: 10  # 保留最近10条消息以避免token过大
  system-message: "You are a helpful assistant. Please respond in plain text without using any Markdown formatting. Do not use asterisks (*), underscores (_), backticks (`), hash symbols (#), or any other Markdown syntax. Provide clear, direct answers in regular plain text format."
  stream: true       # 启用流式输出
  temperature: 0.2   # 温度参数，与用户默认设置保持一致
  max-tokens: 500    # 每次生成的最大token数，与用户默认设置保持一致
