spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  datasource:
    url: jdbc:mysql://localhost:3306/ai_chatting_web?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: abc123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update       # 或者 none / create / create-drop / validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
